#!/bin/bash

exec &> >(tee -a "geninstall.log") 2>geninstall.error

start=0
DRIVE="/dev/sda"
LINKST="https://ftp.rnl.tecnico.ulisboa.pt/pub/gentoo/gentoo-distfiles/releases/amd64/autobuilds/current-stage3-amd64-musl-hardened/"
STAGE3="$(curl $LINKST | sed -n '5p' | cut -d "\"" -f 2)"

USER_NAME=""
PASSWORD=""
LVM_PASSWORD="pass123"
HOSTNAME=""
GIT_USERNAME=""
GIT_EMAIL=""
ESSID=""
WIFI_PASSWORD=""

partition()
{
	sgdisk --zap-all $DRIVE
		sgdisk --clear \
		--new 1::+512M --typecode=1:ef00 --change-name=1:'EFI boot partition' \
		--new 2::-0 --typecode=2:8e00 --change-name=2:'Linux root filesystem' \
		$DRIVE

	mkfs.fat -F32 /dev/sda1

	echo -n "$LVM_PASSWORD" | cryptsetup luksFormat /dev/sda2
	echo -n "$LVM_PASSWORD" | cryptsetup open --type luks /dev/sda2 cryptroot

	mkfs.btrfs -f /dev/mapper/cryptroot
	mount /dev/mapper/cryptroot /mnt/gentoo
	btrfs subvolume create /mnt/gentoo/@
	btrfs subvolume create /mnt/gentoo/@home
	btrfs subvolume create /mnt/gentoo/@var
	btrfs subvolume create /mnt/gentoo/@swap
	btrfs subvolume create /mnt/gentoo/@snapshots

	umount /mnt/gentoo
	mount -o subvol=@,ssd,noatime,compress=zstd,space_cache /dev/mapper/cryptroot /mnt/gentoo
	mkdir /mnt/gentoo/{boot,home,var,swap,.snapshots}
	mount -o subvol=@home,ssd,noatime,compress=zstd,space_cache /dev/mapper/cryptroot /mnt/gentoo/home
	mount -o subvol=@var,ssd,noatime,compress=zstd,space_cache /dev/mapper/cryptroot /mnt/gentoo/var
	mount -o subvol=@snapshots,ssd,noatime,compress=zstd,space_cache /dev/mapper/cryptroot /mnt/gentoo/.snapshots
	mount -o subvol=@swap,ssd,noatime /dev/mapper/cryptroot /mnt/gentoo/swap

	truncate -s 0 /mnt/gentoo/swap/swapfile
	chattr +C /mnt/gentoo/swap/swapfile
	dd if=/dev/zero of=/mnt/gentoo/swap/swapfile bs=1M count=8192 status=progress
	chmod 600 /mnt/gentoo/swap/swapfile
	mkswap /mnt/gentoo/swap/swapfile
	swapon /mnt/gentoo/swap/swapfile

	mkdir /mnt/gentoo/boot/
	mount /dev/sda1 /mnt/gentoo/boot
}

install_base()
{
	cd /mnt/gentoo
  	wget $LINKST/$STAGE3   
  	tar xjvf stage3-*.tar.bz2 --xattrs-include='*.*' --numeric-owner
  	#tar xpvf stage3-*.tar.xz --xattrs-include='*.*' --numeric-owner
  	wget https://raw.githubusercontent.com/sorathpanzer/gentoo/master/genpost
  	chmod +x genpost
  	rm /mnt/gentoo/etc/portage/make.conf
  	echo 'NTHREADS="5"
	FLTO="-flto=${NTHREADS}"
	
ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="@FREE"  
CBUILD="x86_64-gentoo-linux-musl"
CHOST="x86_64-gentoo-linux-musl"
CC="gcc" 
CXX="g++"
#CFCLANG="-march=skylake -O3 ${FLTO} -pipe"
CFLAGS="-march=skylake -O3 -pipe"
CXXFLAGS="${CFLAGS}"
#LDFLAGS="${CFLAGS}"
#AR="llvm-ar"
#NM="llvm-nm"
#RANLIB="llvm-ranlib"
ABI_X86="64"
MAKEOPTS="-j6 -l${NTHREADS}"
PORTAGE_NICENESS="1"
FEATURES="parallel-install"
USE="-kde -qt4 -qt5 -systemd -gnome -gtk -gtk3 -gtk4 -bindist -aqua -cdinstall -cdr -css -dvd -dvdr -a52 -cjk -clamav -coreaudio -ios -ipod \
     -iee1394 -emacs -xemacs -emboss -3dfx -altivec -smartcard -cups -firmware -elogind -sanitize -introspection -vala -java -static -static-libs -ppp btrfs llvm alsa x xinerama"
EMERGE_DEFAULT_OPTS="--quiet-build=y --jobs=${NTHREADS} --load-average=${NTHREADS}"
# NOTE: This stage was built with the bindist Use flag enabled
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
GRUB_PLATFORM="efi-64"
# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C
CURL_SSL="libressl"
# set default languages
LINGUAS="pt pt_PT"
L10N="pt pt-PT"
GENTOO_MIRRORS="https://ftp.rnl.tecnico.ulisboa.pt/pub/gentoo/gentoo-distfiles/ http://ftp.dei.uc.pt/pub/linux/gentoo/"' > /mnt/gentoo/etc/portage/make.conf
	mkdir -p /mnt/gentoo/etc/portage/profile
	rm -r /mnt/gentoo/etc/portage/package.use

	echo "sys-boot/grub device-mapper
dev-vcs/git -gpg
#required by media-libs/mesa-20.0.8::musl
#required by media-libs/libepoxy-1.5.4::gentoo[egl]
#required by x11-base/xorg-server-1.20.8-r1::gentoo[-minimal]
#required by x11-drivers/xf86-input-libinput-0.30.0::gentoo
#required by x11-base/xorg-drivers-1.20-r2::gentoo[input_devices_libinput]
>=media-libs/libglvnd-1.3.2 X
#required by net-misc/networkmanager-1.26.0::musl[wifi,-iwd]
#required by networkmanager (argument)
>=net-wireless/wpa_supplicant-2.9-r2 dbus
#required by x11-libs/gtk+-3.24.20::gentoo
#required by x11-themes/adwaita-icon-theme-3.32.0::gentoo
#required by virtual/freedesktop-icon-theme-0-r3::gentoo
#required by www-client/firefox-bin-79.0::gentoo
#required by firefox-bin (argument)
>=x11-libs/cairo-1.16.0-r4 X
#required by media-sound/pulseaudio-13.0::gentoo[alsa,alsa-plugin]
#required by www-client/firefox-bin-79.0::gentoo
#required by firefox-bin (argument)
>=media-plugins/alsa-plugins-1.2.2 pulseaudio
sys-fs/cryptsetup argon2 gcrypt -libressl -luks1_default -openssl urandom
sys-fs/lvm2 -thin
sys-fs/udisks -lvm
media-libs/harfbuzz icu
media-libs/gd png
# required by Neovim
dev-lua/lpeg luajit
dev-lua/luv luajit
dev-lua/mpack luajit" > /mnt/gentoo/etc/portage/package.use

#echo "# required by firefox-bin (argument)
# /var/db/repos/gentoo/profiles/feature/musl/package.mask: 
# rust-bin requires a glibc system
#>=www-client/firefox-bin-79.0" > /mnt/gentoo/etc/portage/package.unmask

	mkdir --parents /mnt/gentoo/etc/portage/repos.conf
	cp /mnt/gentoo/usr/share/portage/config/repos.conf /mnt/gentoo/etc/portage/repos.conf/gentoo.conf
	cp --dereference /etc/resolv.conf /mnt/gentoo/etc/
	cd
	wget https://raw.githubusercontent.com/YangMame/Gentoo-Installer/master/genfstab
	chmod +x genfstab
	./genfstab -U -p /mnt/gentoo > /mnt/gentoo/etc/fstab 

  	mount --types proc /proc /mnt/gentoo/proc
  	mount --rbind /sys /mnt/gentoo/sys
  	mount --make-rslave /mnt/gentoo/sys
  	mount --rbind /dev /mnt/gentoo/dev
  	mount --make-rslave /mnt/gentoo/dev
}

partition
install_base
#chroot /mnt/gentoo /bin/bash

cat geninstall.error | grep error

runtime="$(($SECONDS / 3600))hrs $((($SECONDS / 60) % 60))min $(($SECONDS % 60))sec"
echo "The system was installed in: $runtime!"
